### ISSUE TITLE
asdasdasads

### ISSUE THREAD

**Issue by oscarwroche** [od-mocks/cool.repo.B#237]
adsadsa

**Comment by oscarwroche** [comment]
This item belongs to payment request #9A6E20 on [OnlyDust](https://www.onlydust.xyz/):
* from [oscarwroche](https://www.onlydust.xyz/) to [oscarwroche](https://www.onlydust.xyz/)
* 2 items included
* $500 for 1 day of work

**Comment by oscarwroche** [comment]
> This item belongs to payment request #9A6E20 on [OnlyDust](https://www.onlydust.xyz/):
> * from [oscarwroche](https://www.onlydust.xyz/) to [oscarwroche](https://www.onlydust.xyz/)
> * 2 items included
> * $500 for 1 day of work

Payment request #9A6E20 has been processed and payment is complete. See you around on [OnlyDust](https://www.onlydust.xyz/).

**Comment by onlydust-contributor** [comment]
This item belongs to payment request #589A0B on [OnlyDust](https://www.onlydust.xyz/):
* from [AnthonyBuisset](https://www.onlydust.xyz/) to [oscarwroche](https://www.onlydust.xyz/)
* 3 items included
* $1,000 for 2 days of work

**Comment by ofux** [comment]
This item belongs to payment request #CC8FDE on [OnlyDust](https://www.onlydust.xyz/):
* from [ofux](https://www.onlydust.xyz/) to [oscarwroche](https://www.onlydust.xyz/)
* 1 item included
* $1,000 for 2 days of work
